# configuration
url: "https://greyhypotheses.github.io"
baseurl: "/greyhypotheses.github.io"


# details
title: greyhypotheses
author: greyhypotheses
github_username: greyhypotheses
description: hypotheses
logo: "/images/uncertainty.png"
tagline: "<a href='https://oll.libertyfund.org'>read</a>, think, analyse, synthesise"


# if include_content is true, the contents of the content.html will be rendered
include_content: true


# layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


# build settings; silently generates a sitemaps.org compliant sitemap for this Jekyll site
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap


# dependencies
markdown: kramdown
mathjax: true
highlighter: rouge


# permalinks
permalink: pretty


